project_id = "mqwkgxrdosqsfkvcynzy"

[functions.generate-session-summary]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false